/hikcam:
  camera:
    ros__parameters:
      device: "usb:0"
      url: "package://unicam/calibration/${NAME}.yaml"
      width: 640
      height: 640
      exposure_time: 2500.
      gamma: 0.7
      timeout: 1.
